apiVersion: apps/v1
kind: Deployment
metadata:
  name: cctns-autosave-producer
spec:
  replicas: 2  # Number of replicas, adjust based on your needs
  selector:
    matchLabels:
      app: cctns-autosave-producer
  template:
    metadata:
      labels:
        app: cctns-autosave-producer
    spec:
      containers:
        - name: cctns-autosave-producer
          image: "$NEXUS_IMAGE_NAME"
          ports:
            - containerPort: 9218
---
apiVersion: v1
kind: Service
metadata:
  name: cctns-autosave-producer
spec:
  selector:
    app: cctns-autosave-producer  # Match the app label from the Deployment
  ports:
    - protocol: TCP
      port: 9218      # Port exposed by the service
      targetPort: 9218 # Container port to route traffic to
  type: ClusterIP  # Internal access within the cluster

