spring.application.name=cctns-autosave-producer-service
server.port=9128

#Fail on unknown properties :
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true

#Logging Config :
logging.level.root=INFO
logging.level.com.cctns.fir.linking.configuration.LoggingAspect=INFO

#DB Config (Encrypted Datasource Password)

#Encryption Config :
encryption.base64.regex=^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$

# Redis Cluster Config
#spring.data.redis.cluster.nodes=10.212.135.82:6369,10.212.135.87:6369
#spring.data.redis.password=NcrbSecure123
#spring.data.redis.cluster.max-redirects=5
#spring.data.redis.timeout=5000ms

# Redis Sentinel Config
spring.data.redis.sentinel.master=mymaster
spring.data.redis.username=default
spring.data.redis.sentinel.nodes=10.212.174.142:26379
spring.data.redis.password=cctns@123
spring.data.redis.timeout=5000ms

# Lettuce Pooling (these stay under spring.redis)
spring.redis.lettuce.pool.max-active=10
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=1
spring.redis.lettuce.pool.max-wait=5s
logging.level.org.springframework.data.redis=INFO

#Redis TTL:
#Redis Fail Safe TTL : 7 Days
autosave.fail-safe.ttl=604800
#Redis Z-Set TTL : 15 min
autosave.z-set.ttl=900

#Autosave Consumer :
autosave-consumer-ms-name=cctns-autosave-consumer-service
autosave-consumer-ms-url=cctns-autosave-consumer-service:9127
autosave-consumer-get-url=/autosave/get/draft-json

#Postgres Application Propreties :
spring.datasource.url=jdbc:postgresql://10.212.135.149:5432/cctns_2_case_mngmnt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.main.allow-bean-definition-overriding=true

#Enviroment Variable
autosave-env-name:DEV-PG
